t/io_uring: remove duplicate definition of gettid()
With a recent change, we now include os.h through nvme.h, and this
can cause a duplicate gettid() definition:

t/io_uring.c:499:12: error: redefinition of ‘gettid’
 static int gettid(void)
            ^~~~~~
In file included from t/../engines/../os/os.h:39,
                 from t/../engines/../thread_options.h:5,
                 from t/../engines/../fio.h:18,
                 from t/../engines/nvme.h:10,
                 from t/io_uring.c:38:
t/../engines/../os/os-linux.h:147:19: note: previous definition of
‘gettid’ was here
 static inline int gettid(void)
                   ^~~~~~

Include os.h directly to make it clear that we use it, and remove the
gettid() definition from io_uring.c.

Reported-by: Yi Zhang <yi.zhang@redhat.com>
Signed-off-by: Jens Axboe <axboe@kernel.dk>