engines/net.c: fix compilation error due to missing signal.h include
Corrects this build failure:

	engines/net.c: In function 'fio_netio_terminate':
	engines/net.c:900:2: warning: implicit declaration of function 'kill' [-Wimplicit-function-declaration]
	engines/net.c:900:16: error: 'SIGUSR2' undeclared (first use in this function)
	engines/net.c:900:16: note: each undeclared identifier is reported only once for each function it appears in

Signed-off-by: Steven Noonan <snoonan@amazon.com>
Signed-off-by: Jens Axboe <axboe@kernel.dk>