configure: fixup clang stupidity
Doesn't like doing _Static_assert() on our structure offset
definition:

error: static_assert expression is not an integral constant expression

Lets just include that in the configure test, so we can avoid using
_Static_assert() if that kind of check fails.

Signed-off-by: Jens Axboe <axboe@fb.com>